// Browser-safe ngtaxkit entrypoint.
// Excludes PDF helpers because they depend on Node-only pdfkit internals.

export {
  vat,
  paye,
  wht,
  pension,
  statutory,
  marketplace,
  payroll,
  rates,
  tools,
  NgtaxkitError,
  InvalidAmountError,
  InvalidCategoryError,
  InvalidServiceTypeError,
  InvalidStateError,
  InvalidPensionRateError,
  InvalidTinError,
  InvalidDateError,
  RateNotFoundError,
  ValidationError,
  ErrorCode,
} from '@ngtaxkit/core';

export type {
  TaxCategory,
  WhtServiceType,
  NigerianState,
  SourceType,
  VerificationStatus,
  SourceConfidence,
  RateSourceValue,
  RateSourceInput,
  RateSourceMetadata,
  RateAuditResult,
  CalculationExplanation,
  TaxBand,
  CommissionBreakdown,
  VatLiability,
  TransactionBreakdown,
  StatePayrollSummary,
  PayrollTotals,
  MonthlyDeductions,
  EmployerCosts,
  ReliefBreakdown,
  VatCalculateOptions,
  VatResult,
  PayeCalculateOptions,
  PayeResult,
  WhtCalculateOptions,
  WhtResult,
  PensionCalculateOptions,
  PensionResult,
  MarketplaceOptions,
  MarketplaceResult,
  EmployeeInput,
  PayrollBatchResult,
  ToolName,
  JsonSchema,
  ToolSchema,
  OpenApiSpec,
  FieldError,
  ErrorCodeValue,
} from '@ngtaxkit/core';

export {
  create,
  validate,
  toFIRSJSON,
  toCSV,
  InvalidQuantityError,
  EmptyInvoiceError,
} from './invoice';

export type {
  Party,
  InvoiceItem,
  ComputedInvoiceItem,
  VatBreakdown,
  ValidationResult,
  ValidationFieldError,
  InvoiceType,
  InvoiceCreateOptions,
  Invoice,
} from './invoice';

export { toUBL } from './xml/ubl';
